"""Signing key providers.

Production keys live in cloud KMS/HSM and are NEVER on a device or in the
repo. The PoC ships a local PEM provider (self-signed dev CA, generated by
scripts/generate_dev_signing_cert.py) plus stubs marking where the KMS
integrations plug in. Rotation policy: docs/key-rotation-runbook.md.
"""
from pathlib import Path
from typing import Protocol

from pyhanko.sign import signers


class SigningKeyProvider(Protocol):
    def get_signer(self) -> signers.SimpleSigner: ...


class LocalPemKeyProvider:
    """Dev/test only: key + cert PEM files on local disk."""

    def __init__(self, key_dir: str):
        self.key_dir = Path(key_dir)

    def get_signer(self) -> signers.SimpleSigner:
        key = self.key_dir / "signing-key.pem"
        cert = self.key_dir / "signing-cert.pem"
        if not key.exists() or not cert.exists():
            raise FileNotFoundError(
                f"Dev signing material not found in {self.key_dir}. "
                "Run: python scripts/generate_dev_signing_cert.py"
            )
        signer = signers.SimpleSigner.load(
            str(key), str(cert), key_passphrase=None
        )
        if signer is None:
            raise ValueError(f"Failed to load signing material from {self.key_dir}")
        return signer


class AwsKmsKeyProvider:
    """Production path: asymmetric signing key held in AWS KMS.

    Implementation notes for the real build:
    - use pyhanko's ExternalSigner with a remote-signing callback that calls
      kms.sign(KeyId=..., MessageType='DIGEST', SigningAlgorithm='RSASSA_PKCS1_V1_5_SHA_256')
    - the certificate chain (internal CA for v1) is stored alongside config;
      only the private key operation goes to KMS
    - IAM policy restricts kms:Sign to the signing service role
    """

    def __init__(self, key_id: str):
        self.key_id = key_id

    def get_signer(self) -> signers.SimpleSigner:
        raise NotImplementedError(
            "AWS KMS signing is a production milestone — see class docstring "
            "and docs/key-rotation-runbook.md"
        )


def provider_from_settings(provider: str, key_dir: str) -> SigningKeyProvider:
    if provider == "local":
        return LocalPemKeyProvider(key_dir)
    if provider == "aws_kms":
        return AwsKmsKeyProvider(key_id="")
    raise ValueError(f"Unknown signing key provider: {provider}")
