"""Signing key providers.

Production keys live in cloud KMS/HSM and are NEVER on a device or in the
repo. The PoC ships a local PEM provider (self-signed dev CA, generated by
scripts/generate_dev_signing_cert.py) plus stubs marking where the KMS
integrations plug in. Rotation policy: docs/key-rotation-runbook.md.
"""
import base64
import binascii
import logging
from pathlib import Path
from typing import Protocol

from pyhanko.sign import signers

logger = logging.getLogger("prowalco.signing")


class SigningKeyProvider(Protocol):
    def get_signer(self) -> signers.SimpleSigner: ...


class LocalPemKeyProvider:
    """Dev/test: key + cert PEM files on local disk. With auto_generate=True
    (diskless PoC hosts) a self-signed dev key is created at first use —
    ephemeral across restarts, loudly logged."""

    def __init__(self, key_dir: str, auto_generate: bool = False):
        self.key_dir = Path(key_dir)
        self.auto_generate = auto_generate

    def get_signer(self) -> signers.SimpleSigner:
        key = self.key_dir / "signing-key.pem"
        cert = self.key_dir / "signing-cert.pem"
        if not key.exists() or not cert.exists():
            if not self.auto_generate:
                raise FileNotFoundError(
                    f"Dev signing material not found in {self.key_dir}. "
                    "Run: python scripts/generate_dev_signing_cert.py"
                )
            logger.warning(
                "SIGNING WITH AN EPHEMERAL DEV KEY (auto-generated at boot, "
                "changes on every restart). PoC only — provide "
                "SIGNING_KEY_PEM_B64/SIGNING_CERT_PEM_B64 or move to KMS "
                "before relying on issued certificates."
            )
            # Imported lazily and path-safely (the scripts/ package is not on
            # sys.path under uvicorn).
            import sys

            backend_dir = str(Path(__file__).resolve().parents[2])
            if backend_dir not in sys.path:
                sys.path.insert(0, backend_dir)
            from scripts.generate_dev_signing_cert import generate

            generate(self.key_dir)
        signer = signers.SimpleSigner.load(str(key), str(cert), key_passphrase=None)
        if signer is None:
            raise ValueError(f"Failed to load signing material from {self.key_dir}")
        return signer


class EnvPemKeyProvider:
    """Key material supplied as base64-encoded PEM env vars — for diskless
    hosts (Render). Decoded to a private tmp dir once and reused."""

    def __init__(self, key_pem_b64: str, cert_pem_b64: str):
        try:
            self._key_pem = base64.b64decode(key_pem_b64, validate=True)
            self._cert_pem = base64.b64decode(cert_pem_b64, validate=True)
        except (binascii.Error, ValueError) as exc:
            raise ValueError("SIGNING_*_PEM_B64 values are not valid base64") from exc
        self._materialized: Path | None = None

    def get_signer(self) -> signers.SimpleSigner:
        if self._materialized is None:
            import tempfile

            d = Path(tempfile.mkdtemp(prefix="signing-"))
            (d / "signing-key.pem").write_bytes(self._key_pem)
            (d / "signing-cert.pem").write_bytes(self._cert_pem)
            self._materialized = d
        signer = signers.SimpleSigner.load(
            str(self._materialized / "signing-key.pem"),
            str(self._materialized / "signing-cert.pem"),
            key_passphrase=None,
        )
        if signer is None:
            raise ValueError("Failed to load signing material from env")
        return signer


class AwsKmsKeyProvider:
    """Production path: asymmetric signing key held in AWS KMS.

    Implementation notes for the real build:
    - use pyhanko's ExternalSigner with a remote-signing callback that calls
      kms.sign(KeyId=..., MessageType='DIGEST', SigningAlgorithm='RSASSA_PKCS1_V1_5_SHA_256')
    - the certificate chain (internal CA for v1) is stored alongside config;
      only the private key operation goes to KMS
    - IAM policy restricts kms:Sign to the signing service role
    """

    def __init__(self, key_id: str):
        self.key_id = key_id

    def get_signer(self) -> signers.SimpleSigner:
        raise NotImplementedError(
            "AWS KMS signing is a production milestone — see class docstring "
            "and docs/key-rotation-runbook.md"
        )


def provider_from_settings(settings) -> SigningKeyProvider:
    # Explicit key material via env vars wins (diskless hosts).
    if settings.signing_key_pem_b64 and settings.signing_cert_pem_b64:
        return EnvPemKeyProvider(settings.signing_key_pem_b64, settings.signing_cert_pem_b64)
    if settings.signing_key_provider == "local":
        return LocalPemKeyProvider(
            settings.signing_key_dir, auto_generate=settings.signing_autogenerate_dev_key
        )
    if settings.signing_key_provider == "aws_kms":
        return AwsKmsKeyProvider(key_id="")
    raise ValueError(f"Unknown signing key provider: {settings.signing_key_provider}")
